# Site Settings
locale                   : "it-IT"
title                    : "AccademiaComeMangi"
title_separator          : "-"
name                     : "Angela Sanson"
description              : ""
url                      : # the base hostname & protocol for your site
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : 
teaser                   :  
breadcrumbs            	 : false
words_per_minute         : 200

# Comments
# https://developers.facebook.com/docs/plugins/comments
comments:
  facebook:
    appid                : 1655693217988910
    num_posts            : 5
    colorscheme          : "light" # "dark"

# SEO Related
google_site_verification : "fQ6Ksp4DVpwSCbDlYezAYYfkjADSADlpkvz-0I20aYs"

# Social Sharing
twitter:
  username               :
facebook:
  username               : 
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-82258738-1"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      author: asanson
      author_profile: true

  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      header: {}

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /blog/categories/:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /blog/categories/

tag_archive:
  type: liquid
  path: /blog/tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development