# Site Settings
locale                   : "it"
title                    : "AccademiaComeMangi"
title_separator          : "-"
name                     : "Angela Sanson"
description              : ""
url                      : "http://www.accademiacomemangi.com"
baseurl                  : ""
repository               : 
teaser                   : "default-teaser.jpg" 
breadcrumbs            	 : false
words_per_minute         : 200
ampdir			 : _amp

# Comments
comments: 
  provider               : "facebook"	
  facebook:
    appid                : 1730727273843220
    num_posts            : 5
    colorscheme          : "light" # "dark"


# SEO Related
google_site_verification : "Q9q4OT2EbWmqObzwSisEezXXowKBdc-oY5Xb5kgX-C4"


# Social Sharing
twitter:
  username		 :
facebook:
  username               : accademiacomemangi@gmail.com
  app_id                 : 1073644766036954
  publisher              : 
og_image                 : # Open Graph/Twitter default site image	      

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-82326236-1"


# Defaults
defaults:
  - scope:
      path: ""
    values:
      author: asanson
      author_profile: true

  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      header: {}

  # _posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sitemap: true
      
# Reading Files
include:
  - .htaccess
  - _pages
  - _plugins
  - _amp
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Outputting
permalink: /blog/categories/:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


category_archive:
  type: liquid
  path: /blog/categories/

tag_archive:
  type: liquid
  path: /blog/tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development